import type { NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Image from "next/image";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Vinos Skapos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex items-center flex-row justify-between p-2">
        <Image src="https://placekitten.com/64/64" alt="Vinos Glassos logo picture" width={64} height={64} />
        <HeaderAvatar />
      </nav>
      <main className="container mx-auto flex flex-col items-center justify-center p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">Vinos Skapos</h1>
        <section className="flex flex-col">
          <Auth0LoginButton />
        </section>
        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
      </main>
    </>
  );
};

const Auth0LoginButton = () => {
  return (
    <button className="px-5 py-2 bg-gray-300 hover:bg-gray-200 rounded" onClick={() => signIn("auth0")}>
      Log in
    </button>
  );
};

const HeaderAvatar = () => {
  const { data: session } = useSession();
  if (session) {
    return (
      <div className="flex items-center">
        <Image
          className="rounded-full"
          src={session.user?.image || "https://placekitten.com/32/32"}
          alt="User profile picture"
          width={32}
          height={32}
        />
        {session.user?.name}
      </div>
    );
  }
  return <div className="flex items-center">Not logged in</div>;
};

export default Home;
